spring.application.name=ToboChatServer

server.port=8081
server.servlet.context-path=/api
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}
aws.cognito.userPoolId=${COGNITO_USER_POOL_ID}
aws.cognito.appClientId=${COGNITO_APP_CLIENT_ID}
aws.s3.bucketName=${BUCKET_NAME}
aws.dynamodb.tableName=${TABLE_NAME}
aws.region=${AWS_REGION:ap-southeast-2}
livekit.api.key=${LIVEKIT_API_KEY}
livekit.api.secret=${LIVEKIT_API_SECRET}

# Cau hinh ket noi toi Neo4j Aura Cloud
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
spring.data.neo4j.database=${NEO4J_DATABASE}

# Cau h\u00ECnh log de theo d\u00F5i c\u00E1c c\u00E2u lenh Cypher  sinh ra (T\u00F9y chon khi debug)
logging.level.org.springframework.data.neo4j=DEBUG

google.gemini.api-key=${GEMINI_API_KEY}
google.gemini.url=${GEMINI_URL}

