spring.application.name=ToboChatServer

server.port=8081
server.servlet.context-path=/api
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}
aws.cognito.userPoolId=${COGNITO_USER_POOL_ID}
aws.cognito.appClientId=${COGNITO_APP_CLIENT_ID}
aws.s3.bucketName=${BUCKET_NAME}
aws.dynamodb.tableName=${TABLE_NAME}
aws.region=${AWS_REGION:ap-southeast-2}
livekit.api.key=${LIVEKIT_API_KEY}
livekit.api.secret=${LIVEKIT_API_SECRET}

# C?u hình k?t n?i t?i Neo4j Aura Cloud
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
spring.data.neo4j.database=${NEO4J_DATABASE}

# C?u hình log ?? theo dõi các câu l?nh Cypher ???c sinh ra (Tùy ch?n khi debug)
logging.level.org.springframework.data.neo4j=DEBUG