spring.application.name=ToboChatServer

server.port=8081
server.servlet.context-path=/api
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI}
aws.cognito.userPoolId=${COGNITO_USER_POOL_ID}
aws.cognito.appClientId=${COGNITO_APP_CLIENT_ID}
aws.s3.bucketName=${BUCKET_NAME}